Repository tinkerbell/pbnj, pull requests merged in 2020-12, with the labels that each got.

#49 Decrease BMC actions timeout
  server/grpcsvr/rpc/bmc.go
Labels: bug

#55 Link to action runs, not the badge
  README.md
Labels: ready-to-merge

#43 Fix panic from client sending nil Auth
  .github/workflows/ci.yaml
  api/v1/bmc.validator.pb.go
  api/v1/common.pb.go
  api/v1/common.proto
  api/v1/common.validator.pb.go
  api/v1/machine.validator.pb.go
  api/v1/task.validator.pb.go
  go.mod
  go.sum
  scripts/Dockerfile.pbbuilder
  scripts/protoc.sh
  server/grpcsvr/rpc/bmc.go
  server/grpcsvr/rpc/bmc_test.go
  server/grpcsvr/rpc/machine.go
  server/grpcsvr/rpc/machine_test.go
  server/grpcsvr/rpc/task.go
  server/grpcsvr/taskrunner/taskrunner.go
Labels: bug

#51 Bugfix timeouts nil pointer exception
  go.mod
  go.sum
  pkg/oob/oob.go
  pkg/oob/oob_test.go
  server/grpcsvr/oob/bmc/bmc.go
  server/grpcsvr/oob/bmc/users_bmclib.go
  server/grpcsvr/oob/machine/machine.go
  server/grpcsvr/oob/machine/machine_power_bmclib.go
  server/grpcsvr/oob/machine/machine_power_redfish.go
  server/grpcsvr/rpc/bmc_test.go
  server/grpcsvr/server_test.go
Labels: bug

#56 Add bmc ip to all log lines
  cmd/pbnj/server.go
  pkg/zaplog/middleware.go
Labels: enhancement
