Repository tinkerbell/pbnj, pull requests merged in 2021-11, with the labels that each got.

#100 Remove monkey patch dep
  Makefile
  go.mod
  grpc/oob/bmc/bmc_test.go
  grpc/oob/machine/machine_test.go
Labels: kind/cleanup

#99 Update bmclib version:
  go.mod
  go.sum
Labels: kind/feature

#103 Add the error message to the client.PowerSet trace
  grpc/oob/machine/machine.go
  grpc/rpc/machine.go
Labels: ready-to-merge

#104 Revert API breaking change:
  api/v1/machine.pb.go
  api/v1/machine.proto
Labels: kind/bug, ready-to-merge, kind/regression, priority/critical-urgent

#105 Fix power on string in cycle check:
  grpc/oob/machine/machine.go
Labels: kind/bug, ready-to-merge, kind/regression, priority/critical-urgent

#107 Tune otel
  grpc/oob/machine/machine.go
Labels: kind/feature, priority/important-soon, ready-to-merge

#108 Pass all RPC span contexts to handlers
  grpc/rpc/bmc.go
  grpc/rpc/machine.go
Labels: ready-to-merge

#109 convert StringSlice attributes to Strings for now
  grpc/oob/machine/machine.go
Labels: ready-to-merge
